### PR TITLE
Merge remote-tracking branch 'refs/remotes/paypal/develop' into develop

### PR DESCRIPTION
**Pull request by nowen094**

### CODE REVIEW

**Comment by bluk** [comment]
There doesn't seem to be any content in this PR, so closing this.

**Comment by nowen094** [comment]
Hey I have had a few conversation today and told them my situation and the
bottom line is that I don't know how to right software I was only supposed
to do beta testing for trading companies but I have tried to make do and
get my payments to show up I think Iam going to call Google this afternoon
because I have not gotten one of my deposits in paypal nor any other
payment platform so if there is anything you can find out for me let me
know otherwise I will be talking with you guys soon thanks

**Comment by nowen094** [comment]
By the way what I need most of all is to finally see a payment that I have
gotten confirmations for and I can finally pay some bills off thanks

**Comment by pp-randy** [comment]
@nowen094 if you are having trouble getting started I think this resource may help https://demo.paypal.com/

**Comment by nowen094** [comment]
Hi,

I'd like to add you to my professional network on LinkedIn.

- Nicola

Confirm that you know Nicola: https://www.linkedin.com/comm/start/accept-invitation?sharedKey=zf48DzEj&invitationId=6206354360293748736&trk=eml-guest-invite-cta&trkEmail=eml-invite_guest-null-2-null-null-0%7Eivrpas29%7Ece








You received an invitation to connect. LinkedIn will use your email address to make suggestions to our members in features like People You May Know. Unsubscribe here: https://www.linkedin.com/e/v2?e=0-ivrpas29-ce&t=lun&midToken=AQFmrFVhGEd36Q&ek=invite_guest&loid=AQGfZF0E7KJw6QAAAViFmzD-4fcw369iYIiJA_Z8jvIicc1mG-lR0J7MdNCzyc0fmA0PD4yQRpORlW5t83CsyjTRFdjwDpr-CXxnV7AguOmpv2Vkb1J-RqucF-pNuSE4se8_3w_jnWCvCb5BjRpZkSfQCMWyf4UkFSfoUwPtN68ZhFgpZQiUb-YuikG1ej7LPJJK&eid=0-ivrpas29-ce


This email was sent to reply@reply.github.com.

If you need assistance or have questions, please contact LinkedIn Customer Service: https://www.linkedin.com/e/v2?e=0-ivrpas29-ce&a=customerServiceUrl&ek=invite_guest

© 2016 LinkedIn Corporation, 1000 West Maude Avenue, Sunnyvale, CA 94085. LinkedIn and the LinkedIn logo are registered trademarks of LinkedIn.

**Pull request closed without merging**
