### PR TITLE
Including Userinfo into SDK and fixing samples

### PR DESCRIPTION
**Pull request by lepipele**

### CODE REVIEW

**Comment by jziaja** [comment]
:+1: 

Thanks @lepipele!  I noticed the model objects for the Userinfo & Address are taken from the [previous Core SDK](https://github.com/paypal/sdk-core-dotnet/tree/master/Source/SDK/OpenIdConnect) and you knew to update the namespace to match this SDK and avoid a conflict with the Core SDK.  I appreciate that!

I noticed the code is still written in .NET 2.0 syntax with the properties all referencing private members.  After I pull this in, I'll update the syntax and remove the redundant private members.

**Comment by lepipele** [comment]
No problem @jziaja!

I did this since documentation (https://developer.paypal.com/docs/integration/direct/identity/) is totally out of sync with this SDK. I'll see if there are any other things like this that I can help with. 
Also, feel free to direct me toward things that you guys need help with - I'll be more than glad to help.

**Comment by jziaja** [comment]
Great to hear @lepipele!  If you do find anything else missing that should be in the SDK, please don't hesitate to submit more pull requests.  Also, if there's anything else with the SDK that you think you can improve upon or refactor to provide a better developer experience, definitely submit pull requests for those ideas. :)

And just to give you a heads up, the one feature I have on hold currently is webhook event validation (I have an internal branch with the validation code that I'll be pushing to this repo once I make the 1.3 release). Our team is in discussions with the webhooks team to better improve the security around the validation, so I'm waiting until those talks are finished to release that feature.

**Comment by lepipele** [comment]
@jziaja Sure thing - I'm not planning to touch webhooks any time soon - still using IPN.

I'm actually the guy that wrote http://www.codeproject.com/Articles/42894/Introduction-to-PayPal-for-C-ASP-NET-developers (one of top results when you google in "C# paypal") - after seeing all the changes to SDK I am thinking to write new article and introduce changes to people since some of them are complaining in comments on stuff not working.

Also, I really think you guys could benefit from more people testing out SDKs - moving to REST was definitely good move but now since documentation is out of sync it's almost impossible to figure out how to use SDK - I know how much problems I've had with integrating that login until I finally figured out that Userinfo class was missing.

Anyways, I'll keep you posted and will try to send more pull requests your way. And thanks for being so responsive here and helping us who try to integrate!

**Comment by jziaja** [comment]
The out-of-sync docs is a known issue with both our team and the docs team.  The docs team is currently working on a revamp of the public docs site, and we're working closely with them to improve how the SDK documentation is both presented and maintained.  @jaypatel512 has been experimenting in providing SDK docs for the PayPal PHP SDK here on GitHub [using the wiki](https://github.com/paypal/PayPal-PHP-SDK/wiki), and we're considering expanding that to the other languages until the PayPal Developer docs are available.

Great to see that you're taking a close look at this SDK, as I agree - it definitely needs more eyes and more developer feedback.  Let me know if you have any questions or need clarification on any SDK or REST documentation when you're working on your article.  Along with improving the documentation here on GitHub, I'd like to add a section on the main readme that points users to other places that might help them.  I'd be more than happy to include a link to your article in that section as well.

**Comment by lepipele** [comment]
OK - I will update you soon with stuff that I'll do in meantime.

Just one thing - who can I message / email if I run into problems with PayPal developer account? Today I've started receiving "We’re sorry, but something went wrong while displaying view/edit page for application. Please try again." whenever I try to Edit/View any app listed in My Apps.

Thanks for all your help and hard work!

**Comment by jziaja** [comment]
It looks like there was some issues with the identity services this morning, but I believe they've cleared it up.  Are you still experiencing the problems?  You can try contacting [PayPal Merchant Technical Support](https://ppmts.custhelp.com/), and they should be able to help you out.

**Comment by jziaja** [comment]
Scratch that, it appears the problem is still present (multiple team members, including myself just now have confirmed that we're seeing it too).  I'm reaching out to the support team to see if anyone has anymore details.  I'll keep you posted on what I find.

**Comment by lepipele** [comment]
Please do - it seems that problem is still not resolved. I'll also try contacting Technical Support and see how that works out.

**Comment by jziaja** [comment]
Services should be working again now.  Let me know if you're still experiencing the problem.

**Comment by lepipele** [comment]
@jziaja Yeah, resolved, just wanted to post here. Thanks for the help!

**Pull request merged**
